name: Insurance API Tests

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run "postman/Motor Insurance API - Postman Automation.postman_collection.json" \
          -e "postman/Insurance QA.postman_environment.json" \
          -r cli
